apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ STORAGE_NAME }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ STORAGE_SIZE }}Gi
{% if STORAGE_TYPE %}
  storageClassName: {{ STORAGE_TYPE }}
{% endif %}
