name: Run Tests

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    strategy:
      matrix:
        python-version: [3.6.1]
    # services:
    #   mongo:
    #     uses: supercharge/mongodb-github-action@1.6.0
    #     ports:
    #       - 27017:27017
    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: "4.4.3"
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Cache dependency
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Requirements
        run: pip install -r requirements.txt 
      - name: Run Tests
        run: make test_reports